# for local development #
version: "2.0"
services:
  db:
    image: "postgres:14.0"
    container_name: "pg"
    restart: always
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_DB=$DB_NAME
    ports:
      - "$DB_PORT:5432"
  queue:
    image: "nats-streaming:0.23.0-alpine3.14"
    container_name: "nats-server"
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"